/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sistema.gestao.escolar.view;

/**
 *
 * @author LENOVO
 */
public class PainelRelatorios extends javax.swing.JPanel {

    /**
     * Creates new form PainelRelatorios
     */
    public PainelRelatorios() {
        initComponents();
        listarBoletimNaTabela("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBoletim = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscaAluno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Consultas e Boletim Escolar");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Busque por estudantes cadastrados para visualizar o boletim completo, médias consolidadas e o status final de aprovação.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        tabelaBoletim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Aluno", "Turma", "Média Geral", "Frquência %", "Situação"
            }
        ));
        jScrollPane1.setViewportView(tabelaBoletim);
        if (tabelaBoletim.getColumnModel().getColumnCount() > 0) {
            tabelaBoletim.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabelaBoletim.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabelaBoletim.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabelaBoletim.getColumnModel().getColumn(3).setPreferredWidth(100);
            tabelaBoletim.getColumnModel().getColumn(4).setPreferredWidth(100);
            tabelaBoletim.getColumnModel().getColumn(5).setPreferredWidth(120);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 798, 191));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBuscaAluno.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Pesquisar Aluno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 800, 180));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nomeBusca = txtBuscaAluno.getText().trim();
        listarBoletimNaTabela(nomeBusca);
    }//GEN-LAST:event_btnBuscarActionPerformed
    
    private void listarBoletimNaTabela(String nomeBusca) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaBoletim.getModel();
        modelo.setNumRows(0);

        try {
            
            
            java.sql.Connection conn = conexao.Conexao.conectar();
            
            String sql = "SELECT a.matricula, a.nome AS aluno_nome, t.nome AS turma_nome, " +
                         "n.media, n.situacao " +
                         "FROM alunos a " +
                         "INNER JOIN turmas t ON a.id_turma = t.id " +
                         "LEFT JOIN notas n ON a.id = n.id_aluno " +
                         "WHERE a.nome LIKE ?";
            
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            
            stmt.setString(1, "%" + nomeBusca + "%");
            
            java.sql.ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String mediaGeral = rs.getString("media") != null ? rs.getString("media") : "S/ Nota";
                String situacao = rs.getString("situacao") != null ? rs.getString("situacao") : "Pendente";
                
                modelo.addRow(new Object[]{
                    rs.getString("matricula"),
                    rs.getString("aluno_nome"),
                    rs.getString("turma_nome"),
                    mediaGeral,
                    situacao
                });
            }

            rs.close(); 
            stmt.close(); 
            conn.close();
            
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao gerar relatório: " + ex.getMessage());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaBoletim;
    private javax.swing.JTextField txtBuscaAluno;
    // End of variables declaration//GEN-END:variables
}
