    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sistema.gestao.escolar.view;

/**
 *
 * @author LENOVO
 */
public class PainelTurmas extends javax.swing.JPanel {

    /**
     * Creates new form PainelTurmas
     */
    public PainelTurmas() {
        initComponents();
    btnSalvarTurmaActionPerformed(null); 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoTurma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeTurma1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPeriodo = new javax.swing.JComboBox<>();
        btnEditarTurma = new javax.swing.JButton();
        btnSalvarTurma = new javax.swing.JButton();
        btnExcluirTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTurmas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Gestão de Turmas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Gerencie as turmas da instituição, defina códigos de identificação exclusivos e associe os períodos letivos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Período/Turno:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 214, -1, -1));

        txtCodigoTurma.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add(txtCodigoTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 167, 422, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Nome da Turma:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 122, -1, -1));

        txtNomeTurma1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add(txtNomeTurma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 122, 422, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Cod. da Turma:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 170, -1, -1));

        cbPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Matutino", "Vespertino", "Noturno" }));
        cbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeriodoActionPerformed(evt);
            }
        });
        add(cbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 213, -1, -1));

        btnEditarTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarTurma.setText("Editar");
        btnEditarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTurmaActionPerformed(evt);
            }
        });
        add(btnEditarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        btnSalvarTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarTurma.setText("Salvar");
        btnSalvarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTurmaActionPerformed(evt);
            }
        });
        add(btnSalvarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        btnExcluirTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluirTurma.setText("Excluir");
        btnExcluirTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTurmaActionPerformed(evt);
            }
        });
        add(btnExcluirTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        tabelaTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Nome da Turma", "Período"
            }
        ));
        jScrollPane1.setViewportView(tabelaTurmas);
        if (tabelaTurmas.getColumnModel().getColumnCount() > 0) {
            tabelaTurmas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaTurmas.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabelaTurmas.getColumnModel().getColumn(2).setPreferredWidth(450);
            tabelaTurmas.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 798, 191));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 800, 220));
        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPeriodoActionPerformed

    private void btnSalvarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTurmaActionPerformed
try {
    String nome = txtNomeTurma1.getText().trim();
    String codigo = txtCodigoTurma.getText().trim();
    if (cbPeriodo.getSelectedItem() == null || nome.isEmpty() || codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de salvar.");
        return;
    }
    String periodo = cbPeriodo.getSelectedItem().toString();

    String sql = "INSERT INTO turma (codigo_turma, nome_turma, turno) VALUES (?, ?, ?)";

    try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        stmt.setString(1, codigo);
        stmt.setString(2, nome);
        stmt.setString(3, periodo);
        stmt.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Turma cadastrada com sucesso!");
        
        // Atualiza a tabela dinamicamente
       // Atualiza a tabela direto aqui dentro
javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaTurmas.getModel();
modelo.setNumRows(0);
String sqlTab = "SELECT id, codigo_turma, nome_turma, turno FROM turma ORDER BY id DESC";
try (java.sql.PreparedStatement stmtTab = conn.prepareStatement(sqlTab);
     java.sql.ResultSet rs = stmtTab.executeQuery()) {
    while (rs.next()) {
        modelo.addRow(new Object[]{rs.getInt("id"), rs.getString("codigo_turma"), rs.getString("nome_turma"), rs.getString("turno")});
    }
}
    }
} catch (java.sql.SQLException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro no banco da Render: " + ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarTurmaActionPerformed

    private void btnEditarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTurmaActionPerformed
try {
    String nome = txtNomeTurma1.getText().trim();
    String codigo = txtCodigoTurma.getText().trim();
    String periodo = cbPeriodo.getSelectedItem().toString();

    if (codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o Código da Turma que deseja editar.");
        return;
    }

    String sql = "UPDATE turma SET nome_turma = ?, turno = ? WHERE codigo_turma = ?";

    try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        stmt.setString(1, nome);
        stmt.setString(2, periodo);
        stmt.setString(3, codigo);
        
        int atualizado = stmt.executeUpdate();
        if (atualizado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Turma atualizada com sucesso!");
            
            // Atualiza a tabela direto aqui dentro
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaTurmas.getModel();
            modelo.setNumRows(0);
            String sqlTab = "SELECT id, codigo_turma, nome_turma, turno FROM turma ORDER BY id DESC";
            try (java.sql.PreparedStatement stmtTab = conn.prepareStatement(sqlTab);
                 java.sql.ResultSet rs = stmtTab.executeQuery()) {
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getInt("id"), rs.getString("codigo_turma"), rs.getString("nome_turma"), rs.getString("turno")});
                }
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Código de turma não encontrado.");
        }
    }
} catch (java.sql.SQLException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao editar: " + ex.getMessage());
}    // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarTurmaActionPerformed

    private void btnExcluirTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTurmaActionPerformed
try {
    String codigo = txtCodigoTurma.getText().trim();

    if (codigo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o Código da Turma que deseja excluir.");
        return;
    }

    int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente excluir a turma " + codigo + "?", "Aviso", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirmar != javax.swing.JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM turma WHERE codigo_turma = ?";

    try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {
        
        stmt.setString(1, codigo);
        int deletado = stmt.executeUpdate();
        
        if (deletado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Turma removida com sucesso.");
            
            // Atualiza a tabela direto aqui dentro
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tabelaTurmas.getModel();
            modelo.setNumRows(0);
            String sqlTab = "SELECT id, codigo_turma, nome_turma, turno FROM turma ORDER BY id DESC";
            try (java.sql.PreparedStatement stmtTab = conn.prepareStatement(sqlTab);
                 java.sql.ResultSet rs = stmtTab.executeQuery()) {
                while (rs.next()) {
                    modelo.addRow(new Object[]{rs.getInt("id"), rs.getString("codigo_turma"), rs.getString("nome_turma"), rs.getString("turno")});
                }
            }
            txtNomeTurma1.setText("");
            txtCodigoTurma.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Código de turma não encontrado.");
        }
    }
} catch (java.sql.SQLException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir: " + ex.getMessage());
}

    }//GEN-LAST:event_btnExcluirTurmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTurma;
    private javax.swing.JButton btnExcluirTurma;
    private javax.swing.JButton btnSalvarTurma;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelaTurmas;
    private javax.swing.JTextField txtCodigoTurma;
    private javax.swing.JTextField txtNomeTurma1;
    // End of variables declaration//GEN-END:variables
}
