
package br.com.sistema.gestao.escolar.view;

/**
 *
 * @author LENOVO
 */
public class PainelAlunos extends javax.swing.JPanel {
    

    /**
     * Creates new form PainelAlunos
     */
    public PainelAlunos() {
        initComponents();
        carregarTurmasNoComboBox();
        listarAlunosNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbTurma = new javax.swing.JComboBox<>();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(940, 556));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Gestão de Alunos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Nome do Aluno:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 110, -1, -1));

        txtMatricula.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 158, 422, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Matrícula:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 156, -1, -1));

        txtNomeAluno.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add(txtNomeAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 110, 422, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Turma:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 204, -1, -1));

        cbTurma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaActionPerformed(evt);
            }
        });
        add(cbTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 204, 200, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 267, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 267, -1, -1));

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 267, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Matrícula", "Nome do Aluno", "Turma"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(350);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 335, 798, 191));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Utilize este painel para cadastrar novos estudantes, vincular turmas obrigatórias e gerenciar os registros da instituição");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 790, 220));
    }// </editor-fold>//GEN-END:initComponents

    private int idAlunoSelecionado = -1;
    
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
                                         
    String itemSelecionado = cbTurma.getSelectedItem().toString();
    String idTexto = itemSelecionado.split(" - ")[0];
    int idTurma = Integer.parseInt(idTexto); 
    String nome = txtNomeAluno.getText().trim();
    String matricula = txtMatricula.getText().trim();

    if (nome.isEmpty() || matricula.isEmpty() || cbTurma.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos obrigatórios!");
        return;
    }

    try {
        java.sql.Connection conn = conexao.Conexao.conectar();
        String sqlVerifica = "SELECT matricula FROM alunos WHERE matricula = ?";
        java.sql.PreparedStatement stmtVerifica = conn.prepareStatement(sqlVerifica);
        stmtVerifica.setString(1, matricula);
        java.sql.ResultSet rs = stmtVerifica.executeQuery();
        
        if (rs.next()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Atenção: A matrícula '" + matricula + "' já esta vinculada a outro aluno!");
                    rs.close();
                    stmtVerifica.close();
                    conn.close();
                    return;
                }

                rs.close();
                stmtVerifica.close();
        
        
        String sql = "INSERT INTO alunos (nome, matricula, id_turma) VALUES (?, ?, ?)";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        
        stmt.setString(1, nome);
        stmt.setString(2, matricula);
       
        stmt.setInt(3, idTurma);

        stmt.executeUpdate();
        stmt.close();
        conn.close();

        javax.swing.JOptionPane.showMessageDialog(this, "Aluno cadastrado com sucesso!");

      
        txtNomeAluno.setText("");
        txtMatricula.setText("");
        if (cbTurma.getItemCount() > 0) {
            cbTurma.setSelectedIndex(-1);
        }
       
        listarAlunosNaTabela();
        
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar aluno: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurmaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    if (idAlunoSelecionado == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, clique em um aluno na tabela abaixo para excluir!");
        return;
    }

    int resposta = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja apagar este aluno do sistema?", 
            "Confirmação de Exclusão", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE);

    if (resposta == javax.swing.JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection conn = conexao.Conexao.conectar();
            
            String sql = "DELETE FROM alunos WHERE id = ?";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
            
            stmt.setInt(1, idAlunoSelecionado);

           
            stmt.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso!");
            
            txtNomeAluno.setText("");
            txtMatricula.setText("");
            cbTurma.setSelectedIndex(-1);
            
            idAlunoSelecionado = -1;
            
            listarAlunosNaTabela();

            stmt.close();
            conn.close();
            
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir aluno: " + ex.getMessage());
        }
    }

        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
                                             
        if (idAlunoSelecionado == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, clique em um aluno na tabela abaixo antes de editar!");
        return;
        }

        String nome = txtNomeAluno.getText().trim();
        String matricula = txtMatricula.getText().trim();

        if (nome.isEmpty() || matricula.isEmpty() || cbTurma.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos e selecione a turma para editar!");
            return;
        }

        String itemSelecionado = cbTurma.getSelectedItem().toString();
        String idTexto = itemSelecionado.split(" - ")[0];
        int idTurma = Integer.parseInt(idTexto);

        try {
            java.sql.Connection conn = conexao.Conexao.conectar();

            String sql = "UPDATE alunos SET nome = ?, matricula = ?, id_turma = ? WHERE id = ?";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, nome);      
            stmt.setString(2, matricula);
            stmt.setInt(3, idTurma);      
            stmt.setInt(4, idAlunoSelecionado);

            stmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Dados do aluno atualizados com sucesso!");

            txtNomeAluno.setText("");
            txtMatricula.setText("");
            cbTurma.setSelectedIndex(-1);

            idAlunoSelecionado = -1; 

            listarAlunosNaTabela();

            stmt.close();
            conn.close();

        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao editar aluno: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnEditarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
                                        
        int linhaSelecionada = jTable1.getSelectedRow();

        if (linhaSelecionada != -1) {
            idAlunoSelecionado = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

            String matricula = jTable1.getValueAt(linhaSelecionada, 1).toString();
            String nome = jTable1.getValueAt(linhaSelecionada, 2).toString();
            String nomeTurma = jTable1.getValueAt(linhaSelecionada, 3).toString();

            txtMatricula.setText(matricula);
            txtNomeAluno.setText(nome);

            for (int i = 0; i < cbTurma.getItemCount(); i++) {
                if (cbTurma.getItemAt(i).contains(nomeTurma)) {
                    cbTurma.setSelectedIndex(i);
                    break;
                }
            }
        }

    }//GEN-LAST:event_jTable1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNomeAluno;
    // End of variables declaration//GEN-END:variables


 
 
    private void carregarTurmasNoComboBox() {


        String sql = "SELECT id, nome FROM turmas"; 


        cbTurma.removeAllItems();


        try (
             java.sql.Connection conn = conexao.Conexao.conectar();
             java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
             java.sql.ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                int id = rs.getInt("id");
                String nomeTurma = rs.getString("nome");

                cbTurma.addItem(id + " - " + nomeTurma);
            }
           cbTurma.setSelectedIndex(-1);

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar turmas: " + e.getMessage());
        }
    }
    private void listarAlunosNaTabela() {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);

        String sql = "SELECT a.id, a.matricula, a.nome AS nome_aluno, t.nome AS nome_turma " +
                     "FROM alunos a " +
                     "INNER JOIN turmas t ON a.id_turma = t.id ORDER BY a.id";


        try (
             java.sql.Connection conn = conexao.Conexao.conectar();
             java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
             java.sql.ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("matricula"),
                    rs.getString("nome_aluno"),
                    rs.getString("nome_turma")
                });
            }

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao listar alunos na tabela: " + e.getMessage());
        }
    }



    }
