/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sistema.gestao.escolar.view;

/**
 *
 * @author LENOVO
 */
public class PainelNotas extends javax.swing.JPanel {

    /**
     * Creates new form PainelNotas
     */
    public PainelNotas() {
        initComponents();
        carregarTurmasNotas();
        listarNotas();
    }

    private void carregarTurmasNotas() {
        try {
            cbTurmaNotas1.removeAllItems();

            String sql = "SELECT nome_turma FROM public.turma ORDER BY nome_turma ASC";

            try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
                 java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
                 java.sql.ResultSet rs = stmt.executeQuery()) {

                while (rs.next()) {
                    cbTurmaNotas1.addItem(rs.getString("nome_turma"));
                }
            }

            carregarAlunosPorTurma();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar turmas nas notas: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void carregarAlunosPorTurma() {
        try {
            cbAlunoNotas.removeAllItems();
            if (cbTurmaNotas1.getSelectedItem() == null) {
                return;
            }

            String turmaSelecionada = cbTurmaNotas1.getSelectedItem().toString();
            String sql = "SELECT nome FROM public.aluno " +
                         "WHERE id_turma = (SELECT id FROM public.turma WHERE nome_turma = ? LIMIT 1) " +
                         "ORDER BY nome ASC";

            try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
                 java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

                stmt.setString(1, turmaSelecionada);
                try (java.sql.ResultSet rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        cbAlunoNotas.addItem(rs.getString("nome"));
                    }
                }
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar alunos: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void listarNotas() {
        try {
            javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tabelaNotas.getModel();
            modelo.setNumRows(0);

            String sql = "SELECT a.nome, n.nota1, n.nota2, n.nota3, n.nota4 " +
                         "FROM public.nota n " +
                         "JOIN public.aluno a ON n.id_aluno = a.id " +
                         "ORDER BY a.nome ASC";

            try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
                 java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
                 java.sql.ResultSet rs = stmt.executeQuery()) {

                while (rs.next()) {
                    double n1 = rs.getDouble("nota1");
                    double n2 = rs.getDouble("nota2");
                    double n3 = rs.getDouble("nota3");
                    double n4 = rs.getDouble("nota4");
                    double media = (n1 + n2 + n3 + n4) / 4.0;
                    String situacao = media >= 7.0 ? "Aprovado" : "Recuperação/Reprovado";

                    modelo.addRow(new Object[]{
                        rs.getString("nome"),
                        n1,
                        n2,
                        n3,
                        n4,
                        String.format("%.2f", media),
                        situacao
                    });
                }
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao listar notas: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void limparCamposNotas() {
        txtNota1.setText("");
        txtNota2.setText("");
        txtNota3.setText("");
        txtNota4.setText("");
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNota4 = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLancar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbTurmaNotas1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbAlunoNotas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNotas = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Lanamento de Notas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Selecione a turma e o aluno para realizar o lanamento das notas bimestrais. A mdia e a situao so calculadas automaticamente.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("Lanamento de Notas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Selecione a turma e o aluno para realizar o lanamento das notas bimestrais. A mdia e a situao so calculadas automaticamente.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("Lanamento de Notas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Selecione a turma e o aluno para realizar o lanamento das notas bimestrais. A mdia e a situao so calculadas automaticamente.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Nota - 04 : ..........................................................................................");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 450, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Nota - 01 : ............................................................................................");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 450, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Nota - 02 : ..........................................................................................");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 460, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Nota - 03 : ..........................................................................................");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 450, -1));
        add(txtNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });
        add(txtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));
        add(txtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));
        add(txtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnLancar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLancar.setText("Gravar Notas");
        btnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Turma:");

        cbTurmaNotas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTurmaNotas1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTurmaNotas1ItemStateChanged(evt);
            }
        });
        cbTurmaNotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaNotas1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Aluno:");

        cbAlunoNotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbAlunoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunoNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(42, 42, 42)
                .addComponent(cbTurmaNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(cbAlunoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlunoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbTurmaNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 800, 230));

        tabelaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Aluno", "Nota 01", "Nota 02", "Nota 03", "Nota 04", "Mdia Final", "Situao"
            }
        ));
        jScrollPane1.setViewportView(tabelaNotas);
        if (tabelaNotas.getColumnModel().getColumnCount() > 0) {
            tabelaNotas.getColumnModel().getColumn(0).setPreferredWidth(300);
            tabelaNotas.getColumnModel().getColumn(1).setPreferredWidth(80);
            tabelaNotas.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabelaNotas.getColumnModel().getColumn(3).setPreferredWidth(80);
            tabelaNotas.getColumnModel().getColumn(4).setPreferredWidth(80);
            tabelaNotas.getColumnModel().getColumn(5).setPreferredWidth(100);
            tabelaNotas.getColumnModel().getColumn(6).setPreferredWidth(120);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 798, 191));
    }// </editor-fold>//GEN-END:initComponents

    private void cbTurmaNotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaNotas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurmaNotas1ActionPerformed

    private void cbAlunoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunoNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlunoNotasActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void btnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarActionPerformed
        try {
            if (cbAlunoNotas.getSelectedItem() == null ||
                txtNota1.getText().trim().isEmpty() ||
                txtNota2.getText().trim().isEmpty() ||
                txtNota3.getText().trim().isEmpty() ||
                txtNota4.getText().trim().isEmpty()) {

                javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos antes de salvar.");
                return;
            }

            String alunoNome = cbAlunoNotas.getSelectedItem().toString();
            double n1 = Double.parseDouble(txtNota1.getText().trim().replace(",", "."));
            double n2 = Double.parseDouble(txtNota2.getText().trim().replace(",", "."));
            double n3 = Double.parseDouble(txtNota3.getText().trim().replace(",", "."));
            double n4 = Double.parseDouble(txtNota4.getText().trim().replace(",", "."));
            double media = (n1 + n2 + n3 + n4) / 4.0;

            String sql = "INSERT INTO public.nota (id_aluno, nota1, nota2, nota3, nota4) " +
                         "VALUES ((SELECT id FROM public.aluno WHERE nome = ? LIMIT 1), ?, ?, ?, ?) " +
                         "ON CONFLICT (id_aluno) DO UPDATE SET " +
                         "nota1 = EXCLUDED.nota1, nota2 = EXCLUDED.nota2, " +
                         "nota3 = EXCLUDED.nota3, nota4 = EXCLUDED.nota4";

            try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao();
                 java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

                stmt.setString(1, alunoNome);
                stmt.setDouble(2, n1);
                stmt.setDouble(3, n2);
                stmt.setDouble(4, n3);
                stmt.setDouble(5, n4);
                stmt.executeUpdate();
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Notas gravadas com sucesso! Média: " + String.format("%.2f", media));
            limparCamposNotas();
            listarNotas();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite apenas números válidos nas notas.");
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao gravar notas: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLancarActionPerformed//GEN-LAST:event_btnLancarActionPerformed

    private void cbTurmaNotas1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTurmaNotas1ItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            carregarAlunosPorTurma();
        }
    }//GEN-LAST:event_cbTurmaNotas1ItemStateChanged//GEN-LAST:event_cbTurmaNotas1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancar;
    private javax.swing.JComboBox<String> cbAlunoNotas;
    private javax.swing.JComboBox<String> cbTurmaNotas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaNotas;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    // End of variables declaration//GEN-END:variables
}
