/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sistema.gestao.escolar.view;

/**
 *
 * @author LENOVO
 */
public class PainelNotas extends javax.swing.JPanel {

    /**
     * Creates new form PainelNotas
     */
    public PainelNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNota4 = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLancar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbTurmaNotas1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbAlunoNotas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Lançamento de Notas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Selecione a turma e o aluno para realizar o lançamento das notas bimestrais. A média e a situação são calculadas automaticamente.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("Lançamento de Notas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Selecione a turma e o aluno para realizar o lançamento das notas bimestrais. A média e a situação são calculadas automaticamente.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("Lançamento de Notas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Selecione a turma e o aluno para realizar o lançamento das notas bimestrais. A média e a situação são calculadas automaticamente.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Nota - 04 : ..........................................................................................");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 450, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Nota - 01 : ............................................................................................");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 450, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Nota - 02 : ..........................................................................................");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 460, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Nota - 03 : ..........................................................................................");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 450, -1));
        add(txtNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });
        add(txtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));
        add(txtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));
        add(txtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnLancar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLancar.setText("Gravar Notas");
        btnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Turma:");

        cbTurmaNotas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTurmaNotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaNotas1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Aluno:");

        cbAlunoNotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbAlunoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunoNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(42, 42, 42)
                .addComponent(cbTurmaNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(cbAlunoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlunoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbTurmaNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 800, 230));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "Nota 01", "Nota 02", "Nota 03", "Nota 04", "Média Final", "Situação"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 798, 191));
    }// </editor-fold>//GEN-END:initComponents

    private void cbTurmaNotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaNotas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTurmaNotas1ActionPerformed

    private void cbAlunoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunoNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAlunoNotasActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void btnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarActionPerformed
try {
    // 1. Validação básica: verifica se tem aluno selecionado
    if (cbAlunoNotas.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um aluno primeiro.");
        return;
    }
    
    String alunoSelecionado = cbAlunoNotas.getSelectedItem().toString();

    // 2. Converte as notas digitadas de String para double (tratando se usarem vírgula)
    double n1 = txtNota1.getText().trim().isEmpty() ? 0.0 : Double.parseDouble(txtNota1.getText().replace(",", "."));
    double n2 = txtNota2.getText().trim().isEmpty() ? 0.0 : Double.parseDouble(txtNota2.getText().replace(",", "."));
    double n3 = txtNota3.getText().trim().isEmpty() ? 0.0 : Double.parseDouble(txtNota3.getText().replace(",", "."));
    double n4 = txtNota4.getText().trim().isEmpty() ? 0.0 : Double.parseDouble(txtNota4.getText().replace(",", "."));

    // 3. SQL inteligente: Tenta dar UPDATE, se não afetar nenhuma linha, faz o INSERT
    String sqlUpdate = "UPDATE nota SET nota1 = ?, nota2 = ?, nota3 = ?, nota4 = ? " +
                       "WHERE id_aluno = (SELECT id FROM aluno WHERE nome = ? LIMIT 1)";
    
    String sqlInsert = "INSERT INTO nota (id_aluno, nota1, nota2, nota3, nota4) " +
                       "VALUES ((SELECT id FROM aluno WHERE nome = ? LIMIT 1), ?, ?, ?, ?)";

    try (java.sql.Connection conn = br.com.sistema.gestao.escolar.factory.Conexao.getConexao()) {
        
        // Tenta atualizar primeiro
        try (java.sql.PreparedStatement stmtUp = conn.prepareStatement(sqlUpdate)) {
            stmtUp.setDouble(1, n1);
            stmtUp.setDouble(2, n2);
            stmtUp.setDouble(3, n3);
            stmtUp.setDouble(4, n4);
            stmtUp.setString(5, alunoSelecionado);
            
            int linhasAfetadas = stmtUp.executeUpdate();
            
            // Se não atualizou nada, significa que o aluno não tem registro na tabela nota. Faz o INSERT.
            if (linhasAfetadas == 0) {
                try (java.sql.PreparedStatement stmtIn = conn.prepareStatement(sqlInsert)) {
                    stmtIn.setString(1, alunoSelecionado);
                    stmtIn.setDouble(2, n1);
                    stmtIn.setDouble(3, n2);
                    stmtIn.setDouble(4, n3);
                    stmtIn.setDouble(5, n4);
                    stmtIn.executeUpdate();
                }
            }
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, "Notas gravadas com sucesso no banco!");
        
        // 4. ATUALIZAR A TABELA DA TELA (jTable1)
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0); // Limpa
        
        String sqlTabela = "SELECT a.id, a.nome, n.nota1, n.nota2, n.nota3, n.nota4, " +
                           "((n.nota1 + n.nota2 + n.nota3 + n.nota4) / 4) AS media_final, " +
                           "CASE WHEN ((n.nota1 + n.nota2 + n.nota3 + n.nota4) / 4) >= 7.0 THEN 'Aprovado' ELSE 'Reprovado' END AS situacao " +
                           "FROM aluno a " +
                           "INNER JOIN nota n ON a.id = n.id_aluno " +
                           "WHERE a.nome = ?";
                           
        try (java.sql.PreparedStatement stmtTab = conn.prepareStatement(sqlTabela)) {
            stmtTab.setString(1, alunoSelecionado);
            try (java.sql.ResultSet rs = stmtTab.executeQuery()) {
                if (rs.next()) {
                    modelo.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("nome"),
                        rs.getDouble("nota1"),
                        rs.getDouble("nota2"),
                        rs.getDouble("nota3"),
                        rs.getDouble("nota4"),
                        String.format("%.2f", rs.getDouble("media_final")),
                        rs.getString("situacao")
                    });
                }
            }
        }
    }

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Formato de nota inválido. Use apenas números.");
} catch (java.sql.SQLException ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro no banco da Render: " + ex.getMessage());
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnLancarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancar;
    private javax.swing.JComboBox<String> cbAlunoNotas;
    private javax.swing.JComboBox<String> cbTurmaNotas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    // End of variables declaration//GEN-END:variables
}
