/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sistema.gestao.escolar.view;

import conexao.Conexao;

/**
 *
 * @author LENOVO
 */
public class PainelTurmas extends javax.swing.JPanel {
   
    private int idTurmaSelecionada = -1;
    
    
    
    /**
     * Creates new form PainelTurmas
     */
    public PainelTurmas() {
        initComponents();
        listarTurmasNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoTurma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeTurma1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPeriodo = new javax.swing.JComboBox<>();
        btnEditarTurma = new javax.swing.JButton();
        btnSalvarTurma = new javax.swing.JButton();
        btnExcluirTurma = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Gestão de Turmas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Gerencie as turmas da instituição, defina códigos de identificação exclusivos e associe os períodos letivos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Período/Turno:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 214, -1, -1));

        txtCodigoTurma.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add(txtCodigoTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 167, 422, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Nome da Turma:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 122, -1, -1));

        txtNomeTurma1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        add(txtNomeTurma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 122, 422, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Cod. da Turma:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 170, -1, -1));

        cbPeriodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Matutino", "Vespertino", "Noturno" }));
        cbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeriodoActionPerformed(evt);
            }
        });
        add(cbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 213, -1, -1));

        btnEditarTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarTurma.setText("Editar");
        btnEditarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTurmaActionPerformed(evt);
            }
        });
        add(btnEditarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        btnSalvarTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarTurma.setText("Salvar");
        btnSalvarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTurmaActionPerformed(evt);
            }
        });
        add(btnSalvarTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        btnExcluirTurma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluirTurma.setText("Excluir");
        btnExcluirTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTurmaActionPerformed(evt);
            }
        });
        add(btnExcluirTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Nome da Turma", "Período"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(450);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 798, 191));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 800, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void cbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPeriodoActionPerformed

    private void btnSalvarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTurmaActionPerformed
        String nome = txtNomeTurma1.getText().trim();
        String codigo = txtCodigoTurma.getText().trim();
        String periodo = cbPeriodo.getSelectedItem().toString();

        if (nome.isEmpty() || codigo.isEmpty() || periodo.equals("-")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha o nome, o código e selecione o período!");
            return;
        }

        try {
            
            java.sql.Connection conn = conexao.Conexao.conectar();

            String sql = "INSERT INTO turmas (codigo_turma, nome, periodo) VALUES (?, ?, ?)";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, codigo);
            stmt.setString(2, nome);
            stmt.setString(3, periodo);

            stmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Turma cadastrada com sucesso!");

            txtNomeTurma1.setText("");
            txtCodigoTurma.setText("");
            cbPeriodo.setSelectedIndex(0);

            listarTurmasNaTabela();

            stmt.close(); conn.close();
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar turma: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnSalvarTurmaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int linhaSelecionada = jTable1.getSelectedRow();
    
        if (linhaSelecionada != -1) {
            idTurmaSelecionada = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());

            String codigo = jTable1.getValueAt(linhaSelecionada, 1).toString();
            String nome = jTable1.getValueAt(linhaSelecionada, 2).toString();
            String periodo = jTable1.getValueAt(linhaSelecionada, 3).toString();

            txtCodigoTurma.setText(codigo);
            txtNomeTurma1.setText(nome);
            cbPeriodo.setSelectedItem(periodo);
        }                              

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnExcluirTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTurmaActionPerformed
        if (idTurmaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, clique em uma turma na tabela abaixo para excluir!");
        return;
        }

        int resposta = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja excluir esta turma?\n(Aviso: Se houver alunos vinculados a turma, não será possivel a exclusão)", 
                "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            try {
                
                java.sql.Connection conn = conexao.Conexao.conectar();

                String sql = "DELETE FROM turmas WHERE id = ?";
                java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setInt(1, idTurmaSelecionada);

                stmt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Turma excluída com sucesso!");

                txtNomeTurma1.setText("");
                txtCodigoTurma.setText("");
                cbPeriodo.setSelectedIndex(0);
                idTurmaSelecionada = -1;

                listarTurmasNaTabela();

                stmt.close(); conn.close();
            } catch (java.sql.SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir turma: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirTurmaActionPerformed

    private void btnEditarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTurmaActionPerformed
        if (idTurmaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, clique em uma turma na tabela abaixo antes de editar!");
            return;
            }

        String nome = txtNomeTurma1.getText().trim();
        String codigo = txtCodigoTurma.getText().trim();
        String periodo = cbPeriodo.getSelectedItem().toString();

        if (nome.isEmpty() || codigo.isEmpty() || periodo.equals("-")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos para editar!");
            return;
            }

        try {
           
            java.sql.Connection conn = conexao.Conexao.conectar();

            String sql = "UPDATE turmas SET codigo_turma = ?, nome = ?, periodo = ? WHERE id = ?";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, codigo);
            stmt.setString(2, nome);
            stmt.setString(3, periodo);
            stmt.setInt(4, idTurmaSelecionada);

            stmt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Turma atualizada com sucesso!");

            txtNomeTurma1.setText("");
            txtCodigoTurma.setText("");
            cbPeriodo.setSelectedIndex(0);
            idTurmaSelecionada = -1; 

            listarTurmasNaTabela();

            stmt.close(); 
            conn.close();
            } catch (java.sql.SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao editar turma: " + ex.getMessage());
            }
        
    }//GEN-LAST:event_btnEditarTurmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarTurma;
    private javax.swing.JButton btnExcluirTurma;
    private javax.swing.JButton btnSalvarTurma;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCodigoTurma;
    private javax.swing.JTextField txtNomeTurma1;
    // End of variables declaration//GEN-END:variables

    private void listarTurmasNaTabela() {
    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
    modelo.setNumRows(0); // 

    try {
       
        java.sql.Connection conn = Conexao.conectar();         
        String sql = "SELECT id, codigo_turma, nome, periodo FROM turmas";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("codigo_turma"),
                rs.getString("nome"),
                rs.getString("periodo")
            });
        }

        rs.close(); stmt.close(); conn.close();
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao listar turmas: " + e.getMessage());
    }
    }


}
