/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.sistema.gestao.escolar.view;

/**
 *
 * @author LENOVO
 */
public class PainelNotas extends javax.swing.JPanel {

    /**
     * Creates new form PainelNotas
     */
    public PainelNotas() {
        initComponents();
        carregarTurmasNoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNota4 = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnLancar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cbTurmaNotas1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbAlunoNotas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("Lançamento de Notas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setText("Selecione a turma e o aluno para realizar o lançamento das notas bimestrais. A média e a situação são calculadas automaticamente.");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("Lançamento de Notas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Selecione a turma e o aluno para realizar o lançamento das notas bimestrais. A média e a situação são calculadas automaticamente.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("Lançamento de Notas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setText("Selecione a turma e o aluno para realizar o lançamento das notas bimestrais. A média e a situação são calculadas automaticamente.");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 584, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setText("Nota - 04 : ..........................................................................................");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 450, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Nota - 01 : ............................................................................................");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 450, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setText("Nota - 02 : ..........................................................................................");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 460, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setText("Nota - 03 : ..........................................................................................");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 450, -1));
        add(txtNota4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, -1, -1));

        txtNota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota1ActionPerformed(evt);
            }
        });
        add(txtNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        txtNota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNota2ActionPerformed(evt);
            }
        });
        add(txtNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));
        add(txtNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnLancar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLancar.setText("Gravar Notas");
        btnLancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Turma:");

        cbTurmaNotas1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbTurmaNotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTurmaNotas1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setText("Aluno:");

        cbAlunoNotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbAlunoNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlunoNotasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(42, 42, 42)
                .addComponent(cbTurmaNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(cbAlunoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLancar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlunoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbTurmaNotas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 800, 230));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "Nota 01", "Nota 02", "Nota 03", "Nota 04", "Média Final", "Situação"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 798, 191));
    }// </editor-fold>//GEN-END:initComponents

    private void cbTurmaNotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTurmaNotas1ActionPerformed
    
        if (cbTurmaNotas1.getSelectedItem() == null) {
        cbAlunoNotas.removeAllItems();
        return;
    }

    String itemSelecionado = cbTurmaNotas1.getSelectedItem().toString();
    String idTexto = itemSelecionado.split(" - ")[0];
    int idTurma = Integer.parseInt(idTexto);

    try { 
        java.sql.Connection conn = conexao.Conexao.conectar();
        
        String sql = "SELECT id, nome FROM alunos WHERE id_turma = ?";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setInt(1, idTurma); 
        
        java.sql.ResultSet rs = stmt.executeQuery();
        
        cbAlunoNotas.removeAllItems();
        
        while (rs.next()) {
            cbAlunoNotas.addItem(rs.getInt("id") + " - " + rs.getString("nome"));
        }
        
        rs.close();
        stmt.close();
        conn.close();
        
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao filtrar alunos: " + ex.getMessage());
    }
    }//GEN-LAST:event_cbTurmaNotas1ActionPerformed

    private void cbAlunoNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlunoNotasActionPerformed
        
    }//GEN-LAST:event_cbAlunoNotasActionPerformed

    private void txtNota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota1ActionPerformed

    private void txtNota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNota2ActionPerformed

    private void btnLancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarActionPerformed
                                              
    if (cbAlunoNotas.getSelectedItem() == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um aluno antes de gravar as notas!");
        return;
    }

    String n1Texto = txtNota1.getText().trim();
    String n2Texto = txtNota2.getText().trim();
    String n3Texto = txtNota3.getText().trim();
    String n4Texto = txtNota4.getText().trim(); 

    if (n1Texto.isEmpty() || n2Texto.isEmpty() || n3Texto.isEmpty() || n4Texto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, insira as quatro notas bimestrais!");
        return; 
    }

    try {
        double n1 = Double.parseDouble(n1Texto.replace(",", "."));
        double n2 = Double.parseDouble(n2Texto.replace(",", "."));
        double n3 = Double.parseDouble(n3Texto.replace(",", "."));
        double n4 = Double.parseDouble(n4Texto.replace(",", "."));

        if (n1 < 0 || n1 > 10 || n2 < 0 || n2 > 10 || n3 < 0 || n3 > 10 || n4 < 0 || n4 > 10) {
            javax.swing.JOptionPane.showMessageDialog(this, "Atenção: As notas devem ser entre 0 e 10!");
            return;
        }

        double media = (n1 + n2 + n3 + n4) / 4.0;
        
        String situacao = "";
        if (media >= 7.0) {
            situacao = "Aprovado";
        } else if (media >= 5.0) {
            situacao = "Recuperação";
        } else {
            situacao = "Reprovado";
        }

        String alunoSelecionado = cbAlunoNotas.getSelectedItem().toString();
        int idAluno = Integer.parseInt(alunoSelecionado.split(" - ")[0]);

        
        
        java.sql.Connection conn = conexao.Conexao.conectar();

        String sql = "INSERT INTO notas (id_aluno, nota1, nota2, nota3, nota4, media, situacao) VALUES (?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);

        stmt.setInt(1, idAluno);
        stmt.setDouble(2, n1);
        stmt.setDouble(3, n2);
        stmt.setDouble(4, n3);
        stmt.setDouble(5, n4);
        stmt.setDouble(6, media);
        stmt.setString(7, situacao);

        stmt.executeUpdate();

        String mediaFormatada = String.format("%.2f", media); 
        javax.swing.JOptionPane.showMessageDialog(this, "Notas salvas com sucesso!\n\nMédia: " + mediaFormatada + "\nSituação: " + situacao);

        txtNota1.setText("");
        txtNota2.setText("");
        txtNota3.setText("");
        txtNota4.setText("");
        cbAlunoNotas.setSelectedIndex(-1);

        stmt.close();
        conn.close();
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite apenas números válidos nas caixas de notas!");
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar no banco de dados: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnLancarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancar;
    private javax.swing.JComboBox<String> cbAlunoNotas;
    private javax.swing.JComboBox<String> cbTurmaNotas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    // End of variables declaration//GEN-END:variables
    
    
    private void carregarTurmasNoComboBox() {
    try {
        String url = "jdbc:mysql://localhost:3306/sistema_gestao_escolar";
        String usuario = "root";
        String senha = "123456"; 
        java.sql.Connection conn = java.sql.DriverManager.getConnection(url, usuario, senha);
        
        String sql = "SELECT id, nome FROM turmas";
        java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
        java.sql.ResultSet rs = stmt.executeQuery();
        
        cbTurmaNotas1.removeAllItems();
        
        while (rs.next()) {
            cbTurmaNotas1.addItem(rs.getInt("id") + " - " + rs.getString("nome"));
        }
         cbTurmaNotas1.setSelectedIndex(-1);
        rs.close();
        stmt.close();
        conn.close();
        
    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar turmas: " + ex.getMessage());
    }
}




}
